// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mq/academy/ent/user"
	"mq/academy/ent/useraccount"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	name      *string
	lastLogin *time.Time
	friends   map[int]struct{}
	account   map[int]struct{}
}

// SetName sets the name field.
func (uc *UserCreate) SetName(s string) *UserCreate {
	uc.name = &s
	return uc
}

// SetLastLogin sets the lastLogin field.
func (uc *UserCreate) SetLastLogin(t time.Time) *UserCreate {
	uc.lastLogin = &t
	return uc
}

// AddFriendIDs adds the friends edge to User by ids.
func (uc *UserCreate) AddFriendIDs(ids ...int) *UserCreate {
	if uc.friends == nil {
		uc.friends = make(map[int]struct{})
	}
	for i := range ids {
		uc.friends[ids[i]] = struct{}{}
	}
	return uc
}

// AddFriends adds the friends edges to User.
func (uc *UserCreate) AddFriends(u ...*User) *UserCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddFriendIDs(ids...)
}

// SetAccountID sets the account edge to UserAccount by id.
func (uc *UserCreate) SetAccountID(id int) *UserCreate {
	if uc.account == nil {
		uc.account = make(map[int]struct{})
	}
	uc.account[id] = struct{}{}
	return uc
}

// SetNillableAccountID sets the account edge to UserAccount by id if the given value is not nil.
func (uc *UserCreate) SetNillableAccountID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetAccountID(*id)
	}
	return uc
}

// SetAccount sets the account edge to UserAccount.
func (uc *UserCreate) SetAccount(u *UserAccount) *UserCreate {
	return uc.SetAccountID(u.ID)
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	if uc.name == nil {
		return nil, errors.New("ent: missing required field \"name\"")
	}
	if uc.lastLogin == nil {
		return nil, errors.New("ent: missing required field \"lastLogin\"")
	}
	if len(uc.account) > 1 {
		return nil, errors.New("ent: multiple assignments on a unique edge \"account\"")
	}
	return uc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	var (
		res sql.Result
		u   = &User{config: uc.config}
	)
	tx, err := uc.driver.Tx(ctx)
	if err != nil {
		return nil, err
	}
	builder := sql.Dialect(uc.driver.Dialect()).
		Insert(user.Table).
		Default()
	if value := uc.name; value != nil {
		builder.Set(user.FieldName, *value)
		u.Name = *value
	}
	if value := uc.lastLogin; value != nil {
		builder.Set(user.FieldLastLogin, *value)
		u.LastLogin = *value
	}
	query, args := builder.Query()
	if err := tx.Exec(ctx, query, args, &res); err != nil {
		return nil, rollback(tx, err)
	}
	id, err := res.LastInsertId()
	if err != nil {
		return nil, rollback(tx, err)
	}
	u.ID = int(id)
	if len(uc.friends) > 0 {
		for eid := range uc.friends {

			query, args := sql.Insert(user.FriendsTable).
				Columns(user.FriendsPrimaryKey[0], user.FriendsPrimaryKey[1]).
				Values(id, eid).
				Values(eid, id).
				Query()
			if err := tx.Exec(ctx, query, args, &res); err != nil {
				return nil, rollback(tx, err)
			}
		}
	}
	if len(uc.account) > 0 {
		eid := keys(uc.account)[0]
		query, args := sql.Update(user.AccountTable).
			Set(user.AccountColumn, id).
			Where(sql.EQ(useraccount.FieldID, eid).And().IsNull(user.AccountColumn)).
			Query()
		if err := tx.Exec(ctx, query, args, &res); err != nil {
			return nil, rollback(tx, err)
		}
		affected, err := res.RowsAffected()
		if err != nil {
			return nil, rollback(tx, err)
		}
		if int(affected) < len(uc.account) {
			return nil, rollback(tx, &ErrConstraintFailed{msg: fmt.Sprintf("one of \"account\" %v already connected to a different \"User\"", keys(uc.account))})
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return u, nil
}
