// Code generated by entc, DO NOT EDIT.

package useraccount

const (
	// Label holds the string label denoting the useraccount type in the database.
	Label = "user_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldPasswd holds the string denoting the passwd vertex property in the database.
	FieldPasswd = "passwd"
	// FieldEmail holds the string denoting the email vertex property in the database.
	FieldEmail = "email"
	// FieldCreatedAt holds the string denoting the createdat vertex property in the database.
	FieldCreatedAt = "created_at"

	// Table holds the table name of the useraccount in the database.
	Table = "user_accounts"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "user_accounts"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
)

// Columns holds all SQL columns are useraccount fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPasswd,
	FieldEmail,
	FieldCreatedAt,
}
