// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldLastLogin holds the string denoting the lastlogin vertex property in the database.
	FieldLastLogin = "last_login"

	// Table holds the table name of the user in the database.
	Table = "users"
	// FriendsTable is the table the holds the friends relation/edge. The primary key declared below.
	FriendsTable = "user_friends"
	// AccountTable is the table the holds the account relation/edge.
	AccountTable = "user_accounts"
	// AccountInverseTable is the table name for the UserAccount entity.
	// It exists in this package in order to avoid circular dependency with the "useraccount" package.
	AccountInverseTable = "user_accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "owner_id"
)

// Columns holds all SQL columns are user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldLastLogin,
}

var (
	// FriendsPrimaryKey and FriendsColumn2 are the table columns denoting the
	// primary key for the friends relation (M2M).
	FriendsPrimaryKey = []string{"user_id", "friend_id"}
)
